# Generated by Django 2.2.7 on 2019-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='teacher/%Y/%m', verbose_name='用户头像'),
        ),
    ]
