# Generated by Django 2.2.7 on 2019-11-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='last_modifed_time',
            new_name='last_modified_time',
        ),
    ]
