# Generated by Django 2.2.7 on 2019-11-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorganization_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='introduction',
            field=models.TextField(default='', verbose_name='讲师简介'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nickname',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='讲师昵称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', max_length=200, upload_to='teacher/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数|粉丝数'),
        ),
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, default='', max_length=30, verbose_name='助教昵称')),
                ('hobby', models.CharField(blank=True, max_length=100, null=True, verbose_name='爱好')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Teacher', verbose_name='讲师')),
            ],
            options={
                'verbose_name': '助教信息表',
                'verbose_name_plural': '助教信息表',
            },
        ),
    ]
