# Generated by Django 2.2.7 on 2019-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20191118_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='image',
            field=models.ImageField(max_length=200, upload_to='org/%Y/%m', verbose_name='机构logo'),
        ),
    ]
