# Generated by Django 2.2.7 on 2019-11-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='created_tiem',
            new_name='created_time',
        ),
    ]
