# Generated by Django 2.2.7 on 2019-11-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191110_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='last_modifed_time',
            new_name='last_modified_time',
        ),
    ]
