# Generated by Django 2.2.7 on 2019-11-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191110_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='last_modifed_time',
            new_name='last_modified_time',
        ),
    ]
