# Generated by Django 2.2.7 on 2019-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
