# Generated by Django 2.2.7 on 2019-11-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20191113_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_video_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='course/video/%Y/%m', verbose_name='本地视频'),
        ),
    ]
