# Generated by Django 2.2.7 on 2019-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_video_local_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频访问地址'),
        ),
    ]
