# Generated by Django 2.2.7 on 2019-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20191115_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='online',
            field=models.DateField(blank=True, null=True, verbose_name='本课程上线时间'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[(1, '实战课'), (2, '免费课'), (0, '其他')], default=0, max_length=1, verbose_name='课程类型'),
        ),
        migrations.AddField(
            model_name='course',
            name='volumn',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
    ]
