# Generated by Django 2.2.7 on 2019-11-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191125_1536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20191112_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='课程外键'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '讲师'), (4, '教程'), (5, '文章')], default=5, verbose_name='收藏类型'),
        ),
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tutorial', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tutorial', verbose_name='教程外键')),
                ('user', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户外键')),
            ],
            options={
                'verbose_name': '用户教程',
                'verbose_name_plural': '用户教程',
            },
        ),
    ]
