# Generated by Django 2.2.7 on 2019-11-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_articlecomment_tutorialcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Article', verbose_name='评论文章外键'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tutorial', verbose_name='评论教程外键'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '讲师'), (4, '教程'), (5, '文章')], default=0, verbose_name='收藏类型'),
        ),
    ]
