# Generated by Django 2.2.7 on 2019-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191114_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_time',
            field=models.PositiveIntegerField(default='0', verbose_name='学习时长（min)'),
        ),
    ]
