# Generated by Django 2.2.7 on 2019-11-22 17:16

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_auto_20191118_1520'),
        ('organization', '0005_auto_20191118_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章標題')),
                ('excerpt', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章详情')),
                ('click_nums', models.IntegerField(default=0, verbose_name='點擊次數')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推薦（文章）')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('desc', models.CharField(max_length=500, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章節名稱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('chapbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tutorial', verbose_name='書的外鍵')),
            ],
            options={
                'verbose_name': '章節',
                'verbose_name_plural': '章節',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='分类名称')),
                ('desc', models.TextField(default='', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '方向'), (2, '技术栈')], verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, verbose_name='是否导航')),
                ('index', models.PositiveSmallIntegerField(default=999, verbose_name='显示顺序（从小到大）')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='blog.Category', verbose_name='父级分类')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='評論內容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='發佈時間')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Article', verbose_name='文章外鍵')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleComment', verbose_name='父級評論')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用戶外鍵')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='文章分類'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='文章標籤'),
        ),
        migrations.AddField(
            model_name='article',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Teacher', verbose_name='授课教师外键'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='多用戶添加外鍵'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Video', verbose_name='文章視頻'),
        ),
    ]
