# Generated by Django 2.2.7 on 2019-11-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20191118_1520'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='文章分類'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.CourseOrganization', verbose_name='课程机构'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='文章標籤'),
        ),
    ]
