# Generated by Django 2.2.7 on 2019-11-24 10:53

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191124_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='教程详情'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=50, verbose_name='教程标题'),
        ),
    ]
