# Generated by Django 2.2.7 on 2019-11-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191124_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.PositiveSmallIntegerField(default=999, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(default='', max_length=200, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='section',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='章节名称'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tutorial', verbose_name='Tutorial外键'),
        ),
    ]
