# Generated by Django 2.2.7 on 2019-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
