# Generated by Django 2.2.7 on 2019-11-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20191123_1738'),
        ('blog', '0010_tutorial_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='course_org',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.CourseOrganization', verbose_name='教程机构'),
        ),
    ]
