# Generated by Django 2.2.7 on 2019-11-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191125_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
