# Generated by Django 2.2.7 on 2019-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='article/%Y/%m', verbose_name='封面图'),
        ),
    ]
