# Generated by Django 2.2.7 on 2019-12-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_cat', to='blog.Category', verbose_name='教程分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击次数'),
        ),
    ]
