# Generated by Django 2.2.7 on 2019-12-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191202_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('download', models.FileField(upload_to='article/resource/%Y/%m', verbose_name='资源文件')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Article', verbose_name='文章外键')),
            ],
            options={
                'verbose_name': '文章资源',
                'verbose_name_plural': '文章资源',
            },
        ),
    ]
