# Generated by Django 2.2.7 on 2019-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_articleresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Area'), (2, 'Technology stack')], verbose_name='类目级别'),
        ),
    ]
